spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/narsingu-suresh/config-repo
          default-label: main
          username: narsingu-suresh
          password: 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

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/