spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${git_hub_repo_link}
          default-label: main
          username: ${git_hub_username}
          password: ${git_hub_personla_access_token}

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/